### ISSUE TITLE
JS fce being offered in a tsx file

### ISSUE THREAD

**Issue by raph90** [mlaursen/vim-react-snippets#7]
When I do 'fce' COC offers me the JS snippet for a functional component instead of the TS version. I'm not sure what the issue is, I have a tsconfig in the directory. I can share my init.vim and other config if required.

**Comment by mlaursen** [comment]
What's the output for `set ft?` in your `.tsx` file? The snippets will only use the TS version for `typescript` and `typecriptreact` file types which makes it seem as if it is still being set to `javascript`/`javascriptreact`.

Sharing your `init.vim` might help me offer some other ideas, but maybe you can try using using these syntax plugins which handle setting filetypes: [.vimrc plugins](https://github.com/mlaursen/dotfiles/blob/a32efb7db85953ba6716b96cc7617d0e1d83128e/.vimrc#L43-L47)
